<?xml version="1.0" ?>

<robot name="RB1" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--
    <xacro:include filename="$(find robot_description)/urdf/robot.gazebo" />
    -->

    <!-- Materials -->
    <material name="blue">
        <color rgba="0 0 ${204/255} 1"/>
    </material>

    <material name="DarkBlue">
        <color rgba="${51/255} ${51/255} ${104/255} 1" />
    </material>

    <material name="red">
        <color rgba="${204/255} 0 0 1"/>
    </material>

    <material name="Grey">
        <color rgba="${153/255} ${153/255} ${153/255} 1" />
    </material>

    <!-- Constants -->
    <xacro:property name="PI" value="3.1415926535897931"/>


    <!-- Link - base -->
    <xacro:property name="base_r" value="0.25" />
    <xacro:property name="base_h" value="0.30" />
    <xacro:property name="base_m" value="20" />
    <link name="base_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${base_m}" />
            <!-- Ix = Iy = 1/12 * m * (3r^2 + h^2) -->
            <!-- Iz = 1/2 * m * r^2 -->
            <inertia
                ixx="${(base_m / 12) * (3 * base_r * base_r + base_h * base_h)}"
                ixy="0"
                ixz="0"
                iyy="${(base_m / 12) * (3 * base_r * base_r + base_h * base_h)}"
                iyz="0"
                izz="${(base_m / 2) * base_r * base_r}" />
        </inertial>

        <collision>
            <geometry>
                <cylinder length="${base_h}" radius="${base_r}"/>
            </geometry>
        </collision>

        <visual>
            <geometry>
                <cylinder length="${base_h}" radius="${base_r}"/>
            </geometry>
            <material name="blue" />
        </visual>
    </link>


    <!-- Joint - base / base_footprint -->
    <joint name="base_to_base_footprint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 -${base_h / 2}" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

    <!-- Link - base_footprint -->
    <link name="base_footprint" />


    <!-- Wheel properties -->
    <xacro:property name="wheel_r" value="${0.05 / 2}" />
    <xacro:property name="wheel_h" value="0.025" />
    <xacro:property name="wheel_m" value="1" />

    <!-- Joint - base / left wheel -->
    <joint name="base_to_left_wheel" type="continuous">
        <origin rpy="0 0 0" xyz="0 -0.2 -${base_h / 2}" />
        <parent link="base_link" />
        <child link="left_wheel" />
        <axis rpy="0 0 0" xyz="0 1 0" />
        <limit effort="10000" velocity="1000" />
        <joint_properties damping="1.0" friction="1.0" />
    </joint>

    <!-- Link - left wheel -->
    <link name="left_wheel">
        <inertial>
            <mass value="${wheel_m}" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <!-- Ix = Iy = 1/12 * m * (3r^2 + h^2) -->
            <!-- Iz = 1/2 * m * r^2 -->
            <inertia
                ixx="${(wheel_m / 12) * (3 * wheel_r * wheel_r + wheel_h * wheel_h)}"
                ixy="0"
                ixz="0"
                iyy="${(wheel_m / 12) * (3 * wheel_r * wheel_r + wheel_h * wheel_h)}"
                iyz="0"
                izz="${(wheel_m / 2) * wheel_r * wheel_r}" />
        </inertial>

        <collision>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_h}" radius="${wheel_r}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_h}" radius="${wheel_r}"/>
            </geometry>
            <material name="red" />
        </visual>
    </link>

    <!-- Joint - base / right wheel -->
    <joint name="base_to_right_wheel" type="continuous">
        <origin rpy="0 0 0" xyz="0 0.2 -${base_h / 2}" />
        <parent link="base_link" />
        <child link="right_wheel" />
        <axis rpy="0 0 0" xyz="0 1 0" />
        <limit effort="10000" velocity="1000" />
        <joint_properties damping="1.0" friction="1.0" />
    </joint>

    <!-- Link - right wheel -->
    <link name="right_wheel">
        <inertial>
            <mass value="${wheel_m}" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <!-- Ix = Iy = 1/12 * m * (3r^2 + h^2) -->
            <!-- Iz = 1/2 * m * r^2 -->
            <inertia
                ixx="${(wheel_m / 12) * (3 * wheel_r * wheel_r + wheel_h * wheel_h)}"
                ixy="0"
                ixz="0"
                iyy="${(wheel_m / 12) * (3 * wheel_r * wheel_r + wheel_h * wheel_h)}"
                iyz="0"
                izz="${(wheel_m / 2) * wheel_r * wheel_r}" />
        </inertial>

        <collision>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_h}" radius="${wheel_r}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_h}" radius="${wheel_r}"/>
            </geometry>
            <material name="red" />
        </visual>
    </link>

    <!-- Caster properties -->
    <xacro:property name="caster_r" value="${0.025 / 2}" />
    <xacro:property name="caster_m" value="1" />

    <!-- Joint - base / front caster -->
    <joint name="base_to_front_caster" type="fixed">
        <origin rpy="0 0 0" xyz="0.1 0 -${base_h / 2}" />
        <parent link="base_link" />
        <child link="front_caster" />
        <axis rpy="0 0 0" xyz="0 1 0" />
        <limit effort="10000" velocity="1000" />
        <joint_properties damping="1.0" friction="0" />
    </joint>

    <!-- Link - front caster -->
    <link name="front_caster">
        <inertial>
            <mass value="${caster_m}" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <!-- Ix = Iy = Iz = 2/5 * m * r^2 -->
            <inertia
                ixx="${(2/5) * caster_m * caster_r * caster_r}"
                ixy="0"
                ixz="0"
                iyy="${(2/5) * caster_m * caster_r * caster_r}"
                iyz="0"
                izz="${(2/5) * caster_m * caster_r * caster_r}" />
        </inertial>

        <!-- Caster wheel support -->
        <collision>
            <origin rpy="0 0 0" xyz="0 0 ${caster_r/2}" />
            <geometry>
                <sphere radius="${caster_r * 2}" />
            </geometry>
        </collision>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 ${caster_r/2}" />
            <geometry>
                <sphere radius="${caster_r * 2}" />
            </geometry>
            <material name="DarkBlue" />
        </visual>

        <!-- Caster wheel -->
        <collision>
            <origin rpy="0 0 0" xyz="0 0 -${caster_r}" />
            <geometry>
                <sphere radius="${caster_r}" />
            </geometry>
        </collision>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 -${caster_r}" />
            <geometry>
                <sphere radius="${caster_r}" />
            </geometry>
            <material name="Grey" />
        </visual>
    </link>

    <!-- Joint - base / back caster -->
    <joint name="base_to_back_caster" type="fixed">
        <origin rpy="0 0 0" xyz="-0.1 0 -${base_h / 2}" />
        <parent link="base_link" />
        <child link="back_caster" />
        <axis rpy="0 0 0" xyz="0 1 0" />
        <limit effort="10000" velocity="1000" />
        <joint_properties damping="1.0" friction="0" />
    </joint>

    <!-- Link - back caster -->
    <link name="back_caster">
        <inertial>
            <mass value="${caster_m}" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <!-- Ix = Iy = Iz = 2/5 * m * r^2 -->
            <inertia
                ixx="${(2/5) * caster_m * caster_r * caster_r}"
                ixy="0"
                ixz="0"
                iyy="${(2/5) * caster_m * caster_r * caster_r}"
                iyz="0"
                izz="${(2/5) * caster_m * caster_r * caster_r}" />
        </inertial>

        <!-- Caster wheel support -->
        <collision>
            <origin rpy="0 0 0" xyz="0 0 ${caster_r/2}" />
            <geometry>
                <sphere radius="${caster_r * 2}" />
            </geometry>
        </collision>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 ${caster_r/2}" />
            <geometry>
                <sphere radius="${caster_r * 2}" />
            </geometry>
            <material name="DarkBlue" />
        </visual>

        <!-- Caster wheel -->
        <collision>
            <origin rpy="0 0 0" xyz="0 0 -${caster_r}" />
            <geometry>
                <sphere radius="${caster_r}" />
            </geometry>
        </collision>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 -${caster_r}" />
            <geometry>
                <sphere radius="${caster_r}" />
            </geometry>
            <material name="Grey" />
        </visual>
    </link>

</robot>